#POST https://phonebook-xutl.onrender.com/api/blogs  HTTP/1.1
POST http://localhost:3003/api/blogs  HTTP/1.1
content-type: application/json

{
    "title":"blog 2",
    "author":"mario",
    "url":"https://fullstackopen.com/",
    "likes":20
}